name: Bundle Size Analyzer

on:
  pull_request:
    branches: [automated-bundle-size]

jobs:
  bundle-size:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Amplify JS
        uses: actions/checkout@v2

      - name: Setup dev
        run: yarn setup-dev
